### ISSUE TITLE
A more complex example?

### ISSUE THREAD

**Issue by brewin** [julianomoraes/componentizationArch#2]
It isn't clear to me how this architecture would work with more complex "components".  A more fleshed-out example, such as a simple to-do list, would be helpful.

**Comment by giorgosTh** [comment]
Indeed! All these mvi / redux architectures sounds good on paper but in complex  scenarios it becomes a different kind of beast.

**Comment by julianomoraes** [comment]
Working on this, more to come in the DroidCon SF

**Comment by giorgosTh** [comment]
Nice looking forward to it!

**Comment by bernaferrari** [comment]
I watched it, but I still think you could have gone deeper into it (like with a RecyclerView or a seek bar instead of play/pause) 

https://youtu.be/1cWwfh_5ZQs

**Comment by jmcaldera** [comment]
How can we use this with other layers of our app architecture like Presenters/ViewModels or should we get rid of them?

Also if we are using UseCases to communicate with a Repository, should we add the UseCases to Activity/Fragments and make the calls there or maybe create a new object/layer that takes a bus and react according given events?

**Comment by timc-mediamonks** [comment]
@julianomoraes are there any updates on this? I am **very** interested in your take on the "more complex" approach 👍

**Comment by bernaferrari** [comment]
I've been using MvRx with some insights from Juliano's approach and couldn't recommend anything else!

**Comment by julianomoraes** [comment]
Stay tuned for this year's Droidcon. :)

**Comment by bernaferrari** [comment]
Which one? 😔

**Comment by julianomoraes** [comment]
Check this out --> https://medium.com/@NetflixTechBlog/making-our-android-studio-apps-reactive-with-ui-components-redux-5e37aac3b244

**Comment by bernaferrari** [comment]
> You read a lot. We like that.
> You’ve reached the end of your free member preview for this month. Upgrade for unlimited access.

Could you please disable the medium paywall for that article?

**Comment by julianomoraes** [comment]
done
