### ISSUE TITLE
Subcomponent implementation

### ISSUE THREAD

**Issue by kyhule** [julianomoraes/componentizationArch#6]
Have you had a situation where you needed to embed a UiComponent/UiView in another UIComponent/UiView? Take for instance your `PrimaryControlsComponent`. What if you wanted to have another screen that would just have the play/pause button but did not need to include the rewind/fast-forward logic?

**Comment by julianomoraes** [comment]
Yes, you can totally put a Component inside another component. Did it not work for you?
