### ISSUE TITLE
List Component solution

### ISSUE THREAD

**Issue by TomMannson** [julianomoraes/componentizationArch#7]
How do you working with some complex lists?
Adapter is android class so in theory should by part of UIView but logic can be quite complex which should not be placed inside View related class because can't be easly tested. Do you recomend to manage Adapter inside UIComponents or UIView?
Another problem is to manage items in that adapter. Each should be a separate SubComponent?

**Comment by julianomoraes** [comment]
Coming soon...

**Comment by julianomoraes** [comment]
Check this out --> https://medium.com/@NetflixTechBlog/making-our-android-studio-apps-reactive-with-ui-components-redux-5e37aac3b244

**Comment by TomMannson** [comment]
Looks nice.
How you are dealing with Global State. It can grows very much for really big app

**Comment by julianomoraes** [comment]
Are you concerned with Memory usage? What is the concern with a bug Global State?

**Comment by TomMannson** [comment]
When it grows to much can be difficult to maintain.

**Comment by TomMannson** [comment]
Ok, I have done my homework. :)
Key to maintainability of "Big" State Object is its good structure.
